from typing import Protocol
from uuid import UUID

from app.modules.users.domain.entity import User


class IUserRepository(Protocol):
    async def find_by_id(self, user_id: UUID) -> User | None: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
